version: "3"

services:
  app:
    image: node:lts-alpine
    user: 1000:1000
    working_dir: /app
    ports:
      - 8000:8000
    depends_on:
      - keycloak
    volumes:
      - .:/app
    command: npm run start:dev

  keycloak:
    image: quay.io/keycloak/keycloak:23.0.6
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev
